name: CONTINUOUS INTEGRATION

on:
  push:
    branches:
      - main

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET_KEY: ${{ secrets.CLOUDINARY_API_SECRET_KEY }}
      REDIS_URI: ${{ secrets.REDIS_URI }}
      JWT_ACCESS_TOKEN_SECRET_KEY: ${{ secrets.JWT_ACCESS_TOKEN_SECRET_KEY }}
      JWT_REFRESH_TOKEN_SECRET_KEY: ${{ secrets.JWT_REFRESH_TOKEN_SECRET_KEY }}
      JWT_RECOVER_SESSION_TOKEN_SECRET_KEY: ${secrets.JWT_RECOVER_SESSION_TOKEN_SECRET_KEY}
      SMTP_HOST: ${secrets.SMTP_HOST}
      SMTP_PORT: ${secrets.SMTP_PORT}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
      - name: Install Dependencies
        run: npm ci

      - name: Format The Code Base
        run: npm run format
      - name: Run Lint Command
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - name: Run Tests Coverage
        run: npm run test:cov
